version: "3.8"

services:
  client:
    build:
      target: base
    command: sh -c "npm start"
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/src/app/src
    environment:
      - NODE_ENV=development

  server:
    build:
      target: base
    command: sh -c "npm run dev"
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/usr/src/app/src
